### Step 1: Install Required Libraries

In [1]:
pip install openpyxl textblob

Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: textblob in c:\users\hp\anaconda3\lib\site-packages (0.20.0)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: nltk>=3.9 in c:\users\hp\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\hp\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.3.2)
Requirement already satisfied: joblib in c:\users\hp\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\hp\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

### Alternative python package, for VADER:

In [3]:
pip install vaderSentiment

Requirement already satisfied: vaderSentiment in c:\users\hp\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests->vaderSentiment) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests->vaderSentiment) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

### Step 2: Import Libraries and Load Data

In [4]:
import pandas as pd
from textblob import TextBlob

# Load CSV
df = pd.read_csv('Web_Scrapping_Task.csv')
df.head()

,Text,Cleaned_Text,Category,Source
0,Paris Saint-Germain clinched a place in the Ch...,paris saintgermain clinched a place champions ...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...
1,Ruiz crashed in a shot from the edge of the ar...,ruiz crashed shot edge area 27th minute parc d...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...
2,Already leading in the tie after Ousmane Dembe...,already leading tie ousmane dembeles goal last...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...
3,"However, Hakimi put the tie beyond Arsenal whe...",however hakimi put tie beyond arsenal scored 7...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...
4,PSG advance to a showdown in Munich on May 31 ...,psg advance showdown munich may 31 inter milan...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...

### Step 3: Define a Function to Get Sentiment

In [5]:
def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

### Step 4: Applying Sentiment Analysis

In [7]:
df['Sentiment'] = df['Cleaned_Text'].apply(get_sentiment)
df.head()

,Text,Cleaned_Text,Category,Source,Sentiment
0,Paris Saint-Germain clinched a place in the Ch...,paris saintgermain clinched a place champions ...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
1,Ruiz crashed in a shot from the edge of the ar...,ruiz crashed shot edge area 27th minute parc d...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Negative
2,Already leading in the tie after Ousmane Dembe...,already leading tie ousmane dembeles goal last...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
3,"However, Hakimi put the tie beyond Arsenal whe...",however hakimi put tie beyond arsenal scored 7...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
4,PSG advance to a showdown in Munich on May 31 ...,psg advance showdown munich may 31 inter milan...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral

### Step 5: Saving the Result to a new file

In [13]:
df.to_csv('Cruz_Tech_Sentiment_Analysis_Results.csv', index=False)

In [9]:
df.head(20)

,Text,Cleaned_Text,Category,Source,Sentiment
0,Paris Saint-Germain clinched a place in the Ch...,paris saintgermain clinched a place champions ...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
1,Ruiz crashed in a shot from the edge of the ar...,ruiz crashed shot edge area 27th minute parc d...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Negative
2,Already leading in the tie after Ousmane Dembe...,already leading tie ousmane dembeles goal last...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
3,"However, Hakimi put the tie beyond Arsenal whe...",however hakimi put tie beyond arsenal scored 7...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
4,PSG advance to a showdown in Munich on May 31 ...,psg advance showdown munich may 31 inter milan...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
5,"Arsenal, meanwhile, saw their European dream c...",arsenal meanwhile saw european dream come end ...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
6,"Still without a trophy since the 2020 FA Cup, ...",still without trophy since 2020 fa cup left pl...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
7,There was an electric atmosphere all evening i...,electric atmosphere evening paris psg able cel...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
8,There was a feverish mood in and around the gr...,feverish mood around ground prematch psg tripp...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Negative
9,"In addition, their top scorer Dembele was not ...",addition top scorer dembele starting lineup co...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
10,"Arsenal, with Thomas Partey back in midfield a...",arsenal thomas partey back midfield missing fi...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
11,"Declan Rice headed just wide, and goalkeeper G...",declan rice headed wide goalkeeper gianluigi d...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
12,"PSG did eventually settle, and they almost wen...",psg eventually settle almost went ahead 17 min...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
13,"Then Doue wasted a great chance, shooting stra...",doue wasted great chance shooting straight dav...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
14,"But PSG did score before the half-hour mark, t...",psg score halfhour mark goal coming wake freek...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
15,Vitinha’s delivery was headed out by Partey bu...,vitinhas delivery headed partey fell ruiz edge...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
16,It was the ideal moment for the 29-year-old Sp...,ideal moment 29yearold spaniard score first ch...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
17,Barcola failed to convert a good chance for th...,barcola failed convert good chance hosts score...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
18,Only another stunning Donnarumma save with his...,another stunning donnarumma save fingertips pr...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
19,German referee Felix Zwayer gave the penalty a...,german referee felix zwayer gave penalty summo...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral

In [12]:
# Run .read_csv to confirm that the csv file has truly been created
df=pd.read_csv('Cruz_Tech_Sentiment_Analysis_Results.csv')

In [11]:
df.head(20)

,Text,Cleaned_Text,Category,Source,Sentiment
0,Paris Saint-Germain clinched a place in the Ch...,paris saintgermain clinched a place champions ...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
1,Ruiz crashed in a shot from the edge of the ar...,ruiz crashed shot edge area 27th minute parc d...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Negative
2,Already leading in the tie after Ousmane Dembe...,already leading tie ousmane dembeles goal last...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
3,"However, Hakimi put the tie beyond Arsenal whe...",however hakimi put tie beyond arsenal scored 7...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
4,PSG advance to a showdown in Munich on May 31 ...,psg advance showdown munich may 31 inter milan...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
5,"Arsenal, meanwhile, saw their European dream c...",arsenal meanwhile saw european dream come end ...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
6,"Still without a trophy since the 2020 FA Cup, ...",still without trophy since 2020 fa cup left pl...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
7,There was an electric atmosphere all evening i...,electric atmosphere evening paris psg able cel...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
8,There was a feverish mood in and around the gr...,feverish mood around ground prematch psg tripp...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Negative
9,"In addition, their top scorer Dembele was not ...",addition top scorer dembele starting lineup co...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
10,"Arsenal, with Thomas Partey back in midfield a...",arsenal thomas partey back midfield missing fi...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
11,"Declan Rice headed just wide, and goalkeeper G...",declan rice headed wide goalkeeper gianluigi d...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
12,"PSG did eventually settle, and they almost wen...",psg eventually settle almost went ahead 17 min...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
13,"Then Doue wasted a great chance, shooting stra...",doue wasted great chance shooting straight dav...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
14,"But PSG did score before the half-hour mark, t...",psg score halfhour mark goal coming wake freek...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
15,Vitinha’s delivery was headed out by Partey bu...,vitinhas delivery headed partey fell ruiz edge...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral
16,It was the ideal moment for the 29-year-old Sp...,ideal moment 29yearold spaniard score first ch...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
17,Barcola failed to convert a good chance for th...,barcola failed convert good chance hosts score...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
18,Only another stunning Donnarumma save with his...,another stunning donnarumma save fingertips pr...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Positive
19,German referee Felix Zwayer gave the penalty a...,german referee felix zwayer gave penalty summo...,Sports,https://www.vanguardngr.com/2025/05/psg-beat-a...,Neutral

### Understanding Public Opinions and Trends Through Sentiment Patterns
##### 1.Overall Public Sentiment Distribution: Out of 20 articles analyzed, 12 (60%) were Positive, 3 (15%) were Negative, and 5 (25%) were Neutral. This indicates a generally favorable public opinion toward PSG's Champions League performance with positive sentiment being the majority of what was encountered

##### 2.Event-Driven Sentiment Spikes: The article covers PSG's victory over Arsenal on May 31, 2025. Positive sentiment was mostly around the description of goals while a lot of negative sentiment existed around  chnaces that weren't taken or missed showing the correlation between event outcome and sentiment analysis .

##### 3.Sentiment Clustering in Text: Negative sentiment appeared early in the article (lines 1, 8) describing players nerves in the game and chances that were not taken , while the majority of positive sentiment (lines 0, 2, 7, 9-13, 16-18) concentrated in the second half or ending of the analysis  .

 ### Using Results to Inform Marketing, Product Development, or Social Insights
##### 1.Marketing Campaign Targeting: With 60% positive sentiment focused on PSG's success, sports brands could target PSG fans with heightened ads during high-sentiment periods especially during victories.

##### 2.Content Performance Optimization: Positive sentiments were especially associated with goals and player performances. It shows that the content team of the club can potentially look into optimizing content performance with content around positive remarks rather than factual reporting.


##### 3.Audience Engagement Strategy: Negative sentiment appeared only in 3 articles (15%), describing player problems or opportunities not taken. This means that marketing can be channelled towards player performances and pivotal moments to increase marketing reach and conversion as the fans showed a bias towards positive sentiment in the analysis.

### Quick Stats Summary from Your Data:
### Metric	Value
##### 1.Total Articles Analyzed	20
##### 2.Positive Sentiment	12 (60%)
##### 3.Negative Sentiment	3 (15%)
##### 4.Neutral Sentiment	5 (25%)
##### 5.Most Positive Topic	PSG Victory & Goals
##### 6.Most Negative Topic	Arsenal's Defeat & Missed Chances
##### 7.Primary Source	
##### Vanguard Nigeria